version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 3
    cooldown:
      default-days: 16
    labels:
      - 'ci'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    open-pull-requests-limit: 3
    cooldown:
      default-days: 16
      semver-major-days: 32
      semver-minor-days: 24
      semver-patch-days: 16
    labels:
      - 'build'
    groups:
      dependencies:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
